baseURL: 'https://balloting.net//'
title: 'Balloting.Net'
theme: 'doks'
languageCode: 'en-us'

params:
  doks:
    backgroundDots: true
    sectionFooter: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  JSON:
    mediaType: "application/json"
    isPlainText: true

sitemap:
  changefreq: monthly
  priority: 0.5
  excludeKinds:
    - taxonomy    # Исключает все страницы таксономий (категории, теги)
    - term        # Исключает все страницы терминов (конкретные теги)
    # - 404       # Если нужно, можно исключить страницу 404
